# Generated by Django 3.1.5 on 2021-03-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='font',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='sans-serif', max_length=20)),
                ('kind', models.CharField(default='webfonts#webfont', max_length=20)),
                ('family', models.CharField(default='Arial', max_length=25, verbose_name='family')),
                ('variants', models.CharField(max_length=25, null=True)),
                ('version', models.CharField(default='v12', max_length=20)),
                ('lastModified', models.DateField()),
                ('files', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
