# Generated by Django 3.1.5 on 2021-03-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasedesign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='font',
            name='variants',
        ),
        migrations.AlterField(
            model_name='font',
            name='family',
            field=models.CharField(default='Arial', max_length=500, verbose_name='family'),
        ),
    ]
