# Generated by Django 3.1.5 on 2021-03-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasedesign', '0002_auto_20210306_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='files',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
