# Generated by Django 3.1.5 on 2021-03-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasedesign', '0003_auto_20210306_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.URLField(max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='font',
            name='files',
        ),
        migrations.AddField(
            model_name='font',
            name='files',
            field=models.ManyToManyField(to='databasedesign.variants'),
        ),
    ]
