# Generated by Django 3.1.5 on 2021-03-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasedesign', '0005_subsets'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='subsets',
            field=models.ManyToManyField(to='databasedesign.subsets'),
        ),
    ]
