# Generated by Django 3.1.5 on 2021-03-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasedesign', '0007_auto_20210307_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.URLField(max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='variants',
            name='files',
        ),
        migrations.AddField(
            model_name='variants',
            name='variants',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='font',
            name='files',
            field=models.ManyToManyField(to='databasedesign.file'),
        ),
    ]
