# Generated by Django 3.1.5 on 2021-03-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasedesign', '0008_auto_20210312_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='font',
            name='files',
        ),
        migrations.RemoveField(
            model_name='font',
            name='subsets',
        ),
        migrations.AddField(
            model_name='variants',
            name='files',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='file',
        ),
    ]
