# Generated by Django 3.1.5 on 2021-03-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasedesign', '0009_auto_20210314_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='subsets',
            field=models.ManyToManyField(to='databasedesign.subsets'),
        ),
        migrations.AddField(
            model_name='font',
            name='variants',
            field=models.ManyToManyField(to='databasedesign.variants'),
        ),
    ]
