# Generated by Django 3.1.5 on 2021-03-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databasedesign', '0010_auto_20210314_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='font',
            name='kind',
        ),
    ]
